config/routes.rb
Rails.application.routes.draw do
#  get 'sessions/new'
#  get 'sessions/create'
#  get 'sessions/destroy'
#  get 'users/index'
#  get 'users/show'
#  get 'users/new'
#  get 'users/create'
  
  root to: 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create] #:index, :show,　　
  
#  resources :tasks, only: [:create, :destroy] #追記した部分
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    
    validates :status, presence: true, length: { maximum: 10 }
    validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 } 
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :tasks 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper #追記した部分
    include Pagy::Backend #追記した部分
    

    
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
    private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in #追加した部分
    before_action :correct_user, only: [:show, :edit, :update, :destroy] #追加した部分
    
    def index
#      @tasks = Task.all
#        if logged_in?
            @tasks = current_user.tasks.all  
#       end
    end
    
    def show
#        @tasks = Task.find(params[:id])
    end
    
    def new
        @task = Task.new
    end
    
    def create
        @task = current_user.tasks.build(tasks_params)    #変更した箇所：correct_user追加　taskをtasksに @tasksをtaskに

        if @task.save
            flash[:success] = 'Task が正常に投稿されました'
            redirect_to @task
    
        else
            flash.now[:danger] = 'Task が投稿されませんでした'
            render :new
        end
    end
    
    def edit
#        @task = Task.find(params[:id])
    end
    
    def update
#        @tasks = Task.find(params[:id])
        
        if @task.update(tasks_params)
            flash[:success] = 'Task は正常に更新されました'
            redirect_to @task
            
        else
            flash.now[:danger] = 'Task は更新されませんでした'
            render :edit
        end
        
    end
    
    def destroy
#        @tasks = Task.find(params[:id])
        @task.destroy
        
        flash[:success] = 'Task は正常に削除されました'
        redirect_to tasks_url
    end
    
    private

    def tasks_params
        params.require(:task).permit(:status, :content)
    end
    
    def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
        unless @task
          redirect_to root_url
        end
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_user_logged_in, only: [:create]  #追記
   
  #def index
  #   @users = pagy(User.order(id: :desc), items: 25)
  #end

  #def show
  #  @user = User.find(params[:id])
  #end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Tasklist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <% if logged_in? %>
        <div class="btn-group">
        <!--    <ul class="navbar-nav">
                <li class="ms-3"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
            </ul>.        -->
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
           <!-- <li class="dropdown-item"><%= link_to 'My profile', task_path(current_user), class: 'nav-link' %></li>.     -->
           <!--     <li class="dropdown-divider"></li>. -->
                <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
        </div>
    <% else %>
        <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        </ul>
    <% end %>
    </div>
    </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
  <body>
      <div class="container">
        <%= render 'layouts/flash_messages' %>

        <%= yield %>
      </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: tasks) do |f| %>

  <% if tasks.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tasks.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% tasks.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status %>
  
  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>

  <%= f.submit '作成' %>
<% end %>

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
  <ul>
    <% tasks.each do |tasks| %>
      <li>
        <div>
          <div>
            <%= link_to tasks.user.name, users_path(tasks.user), class: "text-decoration-none" %> <span class="text-muted">posted at <%= tasks.created_at %></span>
          </div>
          <div>
            <p><%= link_to tasks.id,tasks %>:<%= tasks.status %> &gt; <%= tasks.content %></p>
          </div>
        </div> 
      </li>
    <% end %>
  </ul>

<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render 'form', tasks: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>
<h1>タスク一覧</h1>

    <div>
      <%= render 'tasks/tasks', tasks: @tasks %>
      
      <%= link_to '新規タスクの追加', new_task_path %> 
    </div>
<% else %>
      <h1>Welcome to the Tasklist</h1>
      <%= link_to 'Sign up now!', signup_path %>
<% end %>

<!--
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |tasks| %>
    <li><%= link_to tasks.id,tasks %>:<%= tasks.status %> &gt; <%= tasks.content %></li>
  <% end %>
</ul>

<%= link_to '新規タスクの追加', new_task_path %> 
-->

app/views/tasks/new.html.erb
<h1>作成ページ</h1>

<%= render 'form', tasks: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> の詳細ページ</h1>

<p><%= @task.status %></p>
<p><%= @task.content %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/_form.html.erb
<%= form_with(model: users) do |f| %>  
  
  <% if users.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% users.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
 <%= render 'form', users: @user %>

<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>